
INSERT INTO COURT (ID, NAME, MORNING, AFTERNOON, MORNING_RENTER_ID, AFTERNOON_RENTER_ID, AREA) VALUES (1, 'A', FALSE, FALSE, NULL, NULL, '台中');
INSERT INTO COURT (ID, NAME, MORNING, AFTERNOON, MORNING_RENTER_ID, AFTERNOON_RENTER_ID, AREA) VALUES (2, 'B', FALSE, FALSE, NULL, NULL, '台北');
INSERT INTO COURT (ID, NAME, MORNING, AFTERNOON, MORNING_RENTER_ID, AFTERNOON_RENTER_ID, AREA) VALUES (3, 'C', FALSE, FALSE, NULL, NULL, '台南');

INSERT INTO MANAGER(ID,ACCOUNT,PASSWORD)VALUES(1,'admin','admin');